pl-deoldify

//// 
================================

.. image:: https://img.shields.io/docker/v/fnndsc/pl-deoldify?sort=semver
    :target: https://hub.docker.com/r/fnndsc/pl-deoldify

.. image:: https://img.shields.io/github/license/fnndsc/pl-deoldify
    :target: https://github.com/FNNDSC/pl-deoldify/blob/master/LICENSE

.. image:: https://github.com/FNNDSC/pl-deoldify/workflows/ci/badge.svg
    :target: https://github.com/FNNDSC/pl-deoldify/actions


.. contents:: Table of Contents


.Abstract

DeOldify is an application to colorize images and videos with minimal effort.


.Description

``deoldify`` is a *ChRIS ds-type* application that takes in black and white images and videos, converts them into colored images. 
It can remove glitches, modify the skin tone, and provide a highly detailed and hyper realistic output. 
This application is aids in medical imaging technologies wherein the grayscale medical images are colored and the content is maintained. 


.Prerequisite

* A github account
* A docker account
* A ChRIS store account
* You can either have `docker` or `podman` installed on your system. 

.Configuration Procedure

. Install the latest version of python in your system:
+
----
# dnf install python3
---- 

. Install `cookiecutter`:
+
----
# dnf install cookiecutter
----

. Get the starter code for `cookiecutter`:
+
----
# cookiecutter https://github.com/FNNDSC/cookiecutter-chrisapp.git
----

. Fill out the following options: 
+
* `author_name [FNNDSC]`: The name of the author
* `author_email [dev@babyMRI.org]`: The mail address
* `app_repo_name[pl-app]`: The name of the repository in GitHub. Here, it is `pl-deoldify`. 
* `app_name [deoldify]`: Retain the default application name. Hit enter. 
* `app_python_class_name [Deoldify]`: Retain the default class name. Hit enter. 
* `Select app_type:` Select `ds` for Documentation. 
* `app_title`: Provide the title for this. 
* `app_category []`: Retain the default value. Hit enter. 
* `app_description [An app to ...]`: Provide the abstract for the application. 
* `app_documentation [http://wiki]`: Hit enter 
* `app_version [0.1]`: Select the default. 
* `Select test_automatically`: Choose `1`. 
* `Select publish_automatically`: Choose `1`. 
* `Select platforms`: Choose `1`
+
----
     _            _     _ _  __       
    | |          | |   | (_)/ _|      
  __| | ___  ___ | | __| |_| |_ _   _ 
 / _` |/ _ \/ _ \| |/ _` | |  _| | | |
| (_| |  __/ (_) | | (_| | | | | |_| |
 \__,_|\___|\___/|_|\__,_|_|_|  \__, |
                                 __/ |
                                |___/ 
----

. Edit the `deoldify.py` file: 
+
----
#
# deoldify ds ChRIS plugin app
#
# (c) 2022 Fetal-Neonatal Neuroimaging & Developmental Science Center
#                   Boston Children's Hospital
#
#              http://childrenshospital.org/FNNDSC/
#                        dev@babyMRI.org
#

from chrisapp.base import ChrisApp
import subprocess, os, re
from argparse import ArgumentParser, Namespace, ArgumentDefaultsHelpFormatter

Gstr_title = r"""
     _            _     _ _  __       
    | |          | |   | (_)/ _|      
  __| | ___  ___ | | __| |_| |_ _   _ 
 / _` |/ _ \/ _ \| |/ _` | |  _| | | |
| (_| |  __/ (_) | | (_| | | | | |_| |
 \__,_|\___|\___/|_|\__,_|_|_|  \__, |
                                 __/ |
                                |___/ 
"""

Gstr_synopsis = """

(Edit this in-line help for app specifics. At a minimum, the 
flags below are supported -- in the case of DS apps, both
positional arguments <inputDir> and <outputDir>; for FS and TS apps
only <outputDir> -- and similarly for <in> <out> directories
where necessary.)

    NAME

       deoldify

    SYNOPSIS

        docker run --rm fnndsc/pl-deoldify deoldify                     \\
            [-h] [--help]                                               \\
            [--json]                                                    \\
            [--man]                                                     \\
            [--meta]                                                    \\
            [--savejson <DIR>]                                          \\
            [-v <level>] [--verbosity <level>]                          \\
            [--version]                                                 \\
            <inputDir>                                                  \\
            <outputDir> 

    BRIEF EXAMPLE

        * Bare bones execution

            docker run --rm -u $(id -u)                             \
                -v $(pwd)/in:/incoming -v $(pwd)/out:/outgoing      \
                fnndsc/pl-deoldify deoldify                        \
                /incoming /outgoing

    DESCRIPTION

        `deoldify` ...

    ARGS

        [-h] [--help]
        If specified, show help message and exit.
        
        [--json]
        If specified, show json representation of app and exit.
        
        [--man]
        If specified, print (this) man page and exit.

        [--meta]
        If specified, print plugin meta data and exit.
        
        [--savejson <DIR>] 
        If specified, save json representation file to DIR and exit. 
        
        [-v <level>] [--verbosity <level>]
        Verbosity level for app. Not used currently.
        
        [--version]
        If specified, print version number and exit. 
"""


class Deoldify(ChrisApp):
    """
    An app to colorize images. 
    """
    PACKAGE                 = __package__
    TITLE                   = 'A ChRIS plugin for deoldify'
    CATEGORY                = ''
    TYPE                    = 'ds'
    ICON                    = ''   # url of an icon image
    MIN_NUMBER_OF_WORKERS   = 1    # Override with the minimum number of workers as int
    MAX_NUMBER_OF_WORKERS   = 1    # Override with the maximum number of workers as int
    MIN_CPU_LIMIT           = 2000 # Override with millicore value as int (1000 millicores == 1 CPU core)
    MIN_MEMORY_LIMIT        = 8000  # Override with memory MegaByte (MB) limit as int
    MIN_GPU_LIMIT           = 0    # Override with the minimum number of GPUs as int
    MAX_GPU_LIMIT           = 0    # Override with the maximum number of GPUs as int

    # Use this dictionary structure to provide key-value output descriptive information
    # that may be useful for the next downstream plugin. For example:
    #
    # {
    #   "finalOutputFile":  "final/file.out",
    #   "viewer":           "genericTextViewer",
    # }
    #
    # The above dictionary is saved when plugin is called with a ``--saveoutputmeta``
    # flag. Note also that all file paths are relative to the system specified
    # output directory.
    OUTPUT_META_DICT = {}

    def define_parameters(self):
        """
        Define the CLI arguments accepted by this plugin app.
        Use self.add_argument to specify a new app argument.
        """

    def run(self, options):
        """
        Define the code to be run by this plugin app.
        """
        print(Gstr_title)
        print('Version: %s' % self.get_version())
        print('Conversion of old images to color images %s' % (options.inputdit, options.outputdir))
        for filename in os.listdir(options.inputdir):
            inputpath = os.path.join(options.inputdir, filename)
            outputpath = os.path.join(options.outputdir, re.sub('\.\w+', '.jpg',filename ))
            parser = ArgumentParser("Parse the input arguments for the deoldify script", formatter_class=ArgumentDefaultsHelpFormatter)
            parser.add_argument('--render_factor', type=int, default=35, help='Render factor')

    def show_man_page(self):
        """
        Print the app's man page.
        """
        print(Gstr_synopsis)
----

. Create the input and output directories: 
+
----
# mkdir in out
----

. Run the command specifying the input and output directories: 
+
----
    docker run --rm -u $(id -u)                             \
        -v $(pwd)/in:/incoming -v $(pwd)/out:/outgoing      \
        fnndsc/pl-deoldify deoldify                        \
        /incoming /outgoing
----

. Build `podman` container on the system: 
+
----
# podman build -t local/pl-deoldify .
----

. Optional: Get inline help:
+
----
docker run --rm fnndsc/pl-deoldify deoldify --man
----
 
. You can view the modified images in the output folder. 
