pl-deoldify

//// 
================================

.. image:: https://img.shields.io/docker/v/fnndsc/pl-deoldify?sort=semver
    :target: https://hub.docker.com/r/fnndsc/pl-deoldify

.. image:: https://img.shields.io/github/license/fnndsc/pl-deoldify
    :target: https://github.com/FNNDSC/pl-deoldify/blob/master/LICENSE

.. image:: https://github.com/FNNDSC/pl-deoldify/workflows/ci/badge.svg
    :target: https://github.com/FNNDSC/pl-deoldify/actions


.. contents:: Table of Contents


.Abstract

DeOldify is an application to colorize images and videos with minimal effort.


.Description

``deoldify`` is a *ChRIS ds-type* application that takes in black and white images and videos, converts them into colored images. 
It can remove glitches, modify the skin tone, and provide a highly detailed and hyper realistic output. 
This application is aids in medical imaging technologies wherein the grayscale medical images are colored and the content is maintained. 


.Prerequisite

* A github account
* A docker account
* A ChRIS store account
* You can either have `docker` or `podman` installed on your system. 

.Configuration Procedure

. Install the latest version of python in your system:
+
----
# dnf install python3
---- 

. Install `cookiecutter`:
+
----
# dnf install cookiecutter
----

. Get the starter code for `cookiecutter`:
+
----
# cookiecutter https://github.com/FNNDSC/cookiecutter-chrisapp.git
----

. Fill out the following options: 
+
* `author_name [FNNDSC]`: The name of the author
* `author_email [dev@babyMRI.org]`: The mail address
* `app_repo_name[pl-app]`: The name of the repository in GitHub. Here, it is `pl-deoldify`. 
* `app_name [deoldify]`: Retain the default application name. Hit enter. 
* `app_python_class_name [Deoldify]`: Retain the default class name. Hit enter. 
* `Select app_type:` Select `ds` for Documentation. 
* `app_title`: Provide the title for this. 
* `app_category []`: Retain the default value. Hit enter. 
* `app_description [An app to ...]`: Provide the abstract for the application. 
* `app_documentation [http://wiki]`: Hit enter 
* `app_version [0.1]`: Select the default. 
* `Select test_automatically`: Choose `1`. 
* `Select publish_automatically`: Choose `1`. 
* `Select platforms`: Choose `1`
+
----
     _            _     _ _  __       
    | |          | |   | (_)/ _|      
  __| | ___  ___ | | __| |_| |_ _   _ 
 / _` |/ _ \/ _ \| |/ _` | |  _| | | |
| (_| |  __/ (_) | | (_| | | | | |_| |
 \__,_|\___|\___/|_|\__,_|_|_|  \__, |
                                 __/ |
                                |___/ 
----

. Create the input and output directories: 
+
----
# mkdir in out
----

. Run the command specifying the input and output directories: 
+
----
    docker run --rm -u $(id -u)                             \
        -v $(pwd)/in:/incoming -v $(pwd)/out:/outgoing      \
        fnndsc/SAG-anon deoldify                        \
        /incoming /outgoing
----

. Build `podman` container on the system: 
+
----
# podman build -t local/pl-deoldify .
----

. Optional: Get inline help:
+
----
docker run --rm fnndsc/SAG-anon deoldify --man
----
 
. You can view the modified images in the output folder. 